### ISSUE TITLE
TypeError: dataclass() got an unexpected keyword argument 'frozen'

### ISSUE THREAD

**Issue by SetoKaiba** [google/aqt#502]
I met this problem when I tried to use it.
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/g/Seto/GitHub/LargeWorldModel/LWM/lwm/vision_chat.py", line 18, in <module>
    from lwm.vision_llama import VideoLLaMAConfig, FlaxVideoLLaMAForCausalLM
  File "/mnt/g/Seto/GitHub/LargeWorldModel/LWM/lwm/vision_llama.py", line 21, in <module>
    from lwm.llama import LLaMAConfig, LLAMA_STANDARD_CONFIGS, FlaxLLaMABlockCollection, RMSNorm
  File "/mnt/g/Seto/GitHub/LargeWorldModel/LWM/lwm/llama.py", line 34, in <module>
    import aqt.jax.v2.flax.aqt_flax as aqt
  File "/mnt/g/Seto/GitHub/LargeWorldModel/LWM/venv/lib/python3.10/site-packages/aqt/jax/v2/flax/aqt_flax.py", line 23, in <module>
    from aqt.jax.v2 import aqt_dot_general
  File "/mnt/g/Seto/GitHub/LargeWorldModel/LWM/venv/lib/python3.10/site-packages/aqt/jax/v2/aqt_dot_general.py", line 29, in <module>
    from aqt.jax.v2 import aqt_tensor
  File "/mnt/g/Seto/GitHub/LargeWorldModel/LWM/venv/lib/python3.10/site-packages/aqt/jax/v2/aqt_tensor.py", line 28, in <module>
    from aqt.jax.v2.numerics import no_numerics
  File "/mnt/g/Seto/GitHub/LargeWorldModel/LWM/venv/lib/python3.10/site-packages/aqt/jax/v2/numerics/no_numerics.py", line 23, in <module>
    class NoNumerics(numerics.AqtNumerics):
TypeError: dataclass() got an unexpected keyword argument 'frozen'
```

**Comment by SetoKaiba** [comment]
It's working after I upate flax from 0.7.0 to 0.8.1
