### ISSUE TITLE
Support Python versions <3.10

### ISSUE THREAD

**Issue by mar-muel** [google/aqt#703]
Currently this library requires Python 3.10, but does not specify this in setup.py.

For example with Python 3.9, I receive
```python
Python 3.9.17 | packaged by conda-forge | (main, Aug 10 2023, 07:02:31)
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aqt.jax.v2.flax.aqt_flax as aqt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/martin/miniconda3/envs/sd/lib/python3.9/site-packages/aqt/jax/v2/flax/aqt_flax.py", line 432
    match self.lhs_freeze_mode:
          ^
SyntaxError: invalid syntax
>>> import aqt.jax.v2.config as aqt_config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/martin/miniconda3/envs/sd/lib/python3.9/site-packages/aqt/jax/v2/config.py", line 18, in <module>
    from typing import Literal, Optional, TypeAlias, Union
ImportError: cannot import name 'TypeAlias' from 'typing' (/home/martin/miniconda3/envs/sd/lib/python3.9/typing.py)
```

In general it would be nice to at least support Python 3.8 as it's still quite commonly used as a stable Python version.

**Comment by lukaszlew** [comment]
Thank you!
However we will fix it by requiring 3.10
3.8 is at end of life and 3.9 is not far behind.
https://devguide.python.org/versions/#versions
